<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>BetterDemo.Remote</RootNamespace>
    <AssemblyName>BetterDemo.Remote</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BetterDemo.Core\BetterDemo.Core.csproj" />
  </ItemGroup>
</Project>
